stages:
  - clone
  - build
  - test
  - cleanup

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

clone:
  stage: clone
  script:
    - echo "Cloning GitHub repository..."
    - apk add git
    - git clone https://github.com/DevelopCubeLab/Docker-compose.git .
    - ls -al

build:
  stage: build
  script:
    - echo "Building Docker images..."
    - docker-compose build

test:
  stage: test
  script:
    - echo "Running tests from GitHub repository..."
    - cd tests
    - npm install
    - npm test

cleanup:
  stage: cleanup
  script:
    - echo "Cleaning up resources..."
    - docker-compose down
  when: always
