stages:
  - build
  - test
  - cleanup

variables:
  DOCKER_HOST: unix:///var/run/docker.sock

build:
  stage: build
  script:
    - echo "Building Docker images..."
    - docker-compose build

test:
  stage: test
  script:
    - echo "Starting services for testing..."
    - docker-compose up -d
    - echo "Running tests..."
    - cd tests
    - npm install
    - npm test
  after_script:
    - echo "Stopping services after tests..."
    - docker-compose down

cleanup:
  stage: cleanup
  script:
    - echo "Cleaning up resources..."
    - docker-compose down
  when: always
