stages:
  - build
  - deploy
  - test
  - cleanup

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - apk add --no-cache docker-compose
  - docker info
  - docker-compose build
  - docker-compose up -d

build:
  stage: build
  script:
    - echo "Building Docker images..."
    - docker-compose build

deploy:
  stage: deploy
  script:
    - echo "Deploying services..."
    - docker-compose up -d
  rules:
    - if: $CI_COMMIT_BRANCH == "project"

test:
  stage: test
  script:
    - echo "Running tests in tests directory..."
    - cd tests
    - npm install
    - npm test
  dependencies:
    - deploy

cleanup:
  stage: cleanup
  script:
    - echo "Stopping and cleaning up containers..."
    - docker-compose down
  when: always
