stages:
  - build
  - deploy
  - test
  - cleanup

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:dind
    command: ["--privileged"]

before_script:
  - docker info

build:
  stage: build
  script:
    - echo "Building Docker images..."
    - docker-compose build 

deploy:
  stage: deploy
  script:
    - echo "Deploying services..."
    - docker-compose up -d
  rules:
    - if: $CI_COMMIT_BRANCH == "project" 

test:
  stage: test
  script:
    - echo "Running tests..."
    - docker ps
    - docker-compose exec app npm test
  dependencies:
    - deploy

cleanup:
  stage: cleanup
  script:
    - echo "Cleaning up containers..."
    - docker-compose down
  when: always
