stages:
  - clone
  - build
  - test
  - cleanup

clone:
  stage: clone
  script:
    - echo "Cloning GitHub repository..."
    - git clone https://github.com/DevelopCubeLab/Docker-compose.git .
    - ls -al

build:
  stage: build
  script:
    - echo "Building Docker images..."
    - docker-compose build

test:
  stage: test
  script:
    - echo "Running tests..."
    - cd tests
    - npm install
    - npm test

cleanup:
  stage: cleanup
  script:
    - echo "Cleaning up resources..."
    - docker-compose down
  when: always
