stages:
  - build
  - test
  - cleanup

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  script:
    - echo "Building Docker images..."
    - docker-compose build

test:
  stage: test
  script:
    - echo "Running tests..."
    - cd tests
    - npm install
    - npm test

cleanup:
  stage: cleanup
  script:
    - echo "Cleaning up resources..."
    - docker-compose down
  when: always
