version: '1'
services:
  service1:
    build:
      context: ./server1    # service 1 folder
    ports:
      - "8199:8199"
    depends_on:
      - service2
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  service2:
    build:
      context: ./server2     # service 2 folder
    expose:
      - "5000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
